title: "Rudof tutorials"
author: "Jose Emilio Labra Gayo"
logo: images/diagram.png

execute:
  execute_notebooks: "off"

html:
  favicon: images/diagram.png
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  repository_url: "https://github.com/rudof-project/tutorials"
  repository_branch: main
  path_to_book: book/

launch_buttons:
  colab_url: "https://colab.research.google.com"
